import type { RequestTemplate, RequestRecord } from "./types";

export const mockTemplates: RequestTemplate[] = [
  {
    id: "tmpl-001",
    name: "Trancamento de Matrícula",
    description: "Solicitação para trancamento temporário da matrícula.",
    category: "Acadêmico",
    createdAt: "2026-04-01",
    updatedAt: "2026-04-01",
    isActive: true,
    fields: [
      {
        id: "field-001",
        fieldKey: "motivo_trancamento",
        label: "Motivo do Trancamento",
        type: "textarea",
        required: true,
        placeholder: "Descreva o motivo do trancamento",
      },
      {
        id: "field-002",
        fieldKey: "periodo_trancamento",
        label: "Período de Trancamento",
        type: "select",
        required: true,
        options: [
          { label: "1 semestre", value: "1_semestre" },
          { label: "2 semestres", value: "2_semestres" },
          { label: "1 ano", value: "1_ano" },
        ],
      },
      {
        id: "field-003",
        fieldKey: "data_inicio",
        label: "Data de Início",
        type: "date",
        required: true,
      },
    ],
  },

  {
    id: "tmpl-002",
    name: "Segunda Chamada de Prova",
    description: "Solicitação para realização de prova em segunda chamada.",
    category: "Acadêmico",
    createdAt: "2026-04-01",
    updatedAt: "2026-04-02",
    isActive: true,
    fields: [
      {
        id: "field-004",
        fieldKey: "disciplina",
        label: "Disciplina",
        type: "text",
        required: true,
        placeholder: "Digite o nome da disciplina",
      },
      {
        id: "field-005",
        fieldKey: "professor_responsavel",
        label: "Professor Responsável",
        type: "text",
        required: true,
        placeholder: "Digite o nome do professor",
      },
      {
        id: "field-006",
        fieldKey: "data_prova_original",
        label: "Data da Prova Original",
        type: "date",
        required: true,
      },
      {
        id: "field-007",
        fieldKey: "justificativa",
        label: "Justificativa",
        type: "textarea",
        required: true,
        placeholder: "Explique o motivo da ausência",
      },
      {
        id: "field-008",
        fieldKey: "documento_comprobatorio",
        label: "Documento Comprobatório",
        type: "file",
        required: true,
        description: "Atestado médico, declaração ou documento equivalente.",
      },
    ],
  },

  {
    id: "tmpl-003",
    name: "Declaração de Matrícula",
    description: "Solicitação de declaração de vínculo acadêmico.",
    category: "Documentos",
    createdAt: "2026-04-03",
    updatedAt: "2026-04-03",
    isActive: true,
    fields: [
      {
        id: "field-009",
        fieldKey: "finalidade",
        label: "Finalidade",
        type: "select",
        required: true,
        options: [
          { label: "Trabalho", value: "trabalho" },
          { label: "Estágio", value: "estagio" },
          { label: "Financiamento", value: "financiamento" },
          { label: "Outros", value: "outros" },
        ],
      },
      {
        id: "field-010",
        fieldKey: "quantidade_copias",
        label: "Quantidade de Cópias",
        type: "number",
        required: true,
        placeholder: "Informe a quantidade",
      },
      {
        id: "field-011",
        fieldKey: "observacoes",
        label: "Observações",
        type: "textarea",
        required: false,
        placeholder: "Informações adicionais",
      },
    ],
  },

  {
    id: "tmpl-004",
    name: "Aproveitamento de Disciplina",
    description: "Solicitação para aproveitamento de créditos cursados em outra instituição.",
    category: "Acadêmico",
    createdAt: "2026-04-04",
    updatedAt: "2026-04-04",
    isActive: true,
    fields: [
      {
        id: "field-012",
        fieldKey: "disciplina_aproveitada",
        label: "Disciplina a ser Aproveitada",
        type: "text",
        required: true,
        placeholder: "Digite a disciplina cursada",
      },
      {
        id: "field-013",
        fieldKey: "instituicao_origem",
        label: "Instituição de Origem",
        type: "text",
        required: true,
        placeholder: "Digite a instituição de origem",
      },
      {
        id: "field-014",
        fieldKey: "carga_horaria",
        label: "Carga Horária",
        type: "number",
        required: true,
        placeholder: "Ex.: 60",
      },
      {
        id: "field-015",
        fieldKey: "nota_obtida",
        label: "Nota Obtida",
        type: "number",
        required: true,
        placeholder: "Ex.: 8.5",
      },
      {
        id: "field-016",
        fieldKey: "historico_escolar",
        label: "Histórico Escolar",
        type: "file",
        required: true,
        description: "Envie o histórico escolar da instituição de origem em PDF.",
      },
      {
        id: "field-017",
        fieldKey: "ementa_disciplina",
        label: "Ementa da Disciplina",
        type: "file",
        required: true,
        description: "Envie a ementa da disciplina cursada em PDF.",
      },
    ],
  },
];

export const mockRequests: RequestRecord[] = [
  {
    id: "req-001",
    templateId: "tmpl-001",
    templateName: "Trancamento de Matrícula",
    submittedBy: "João Silva",
    submittedAt: "2026-04-10",
    status: "pending",
    data: {
      motivo_trancamento: "Questões de saúde pessoal.",
      periodo_trancamento: "1_semestre",
      data_inicio: "2026-05-01",
    },
  },
  {
    id: "req-002",
    templateId: "tmpl-002",
    templateName: "Segunda Chamada de Prova",
    submittedBy: "Maria Santos",
    submittedAt: "2026-04-11",
    status: "approved",
    data: {
      disciplina: "Cálculo II",
      professor_responsavel: "Dr. Carlos Lima",
      data_prova_original: "2026-04-08",
      justificativa: "Internação hospitalar no dia da avaliação.",
    },
  },
  {
    id: "req-003",
    templateId: "tmpl-003",
    templateName: "Declaração de Matrícula",
    submittedBy: "Pedro Costa",
    submittedAt: "2026-04-12",
    status: "in_progress",
    data: {
      finalidade: "estagio",
      quantidade_copias: 2,
      observacoes: "Necessário para entrega no RH.",
    },
  },
];